/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    MvCardHeader: typeof import('./src/@core/components/MvCardHeader.vue')['default']
    MvDataTable: typeof import('./src/@core/components/MvDataTable.vue')['default']
    MVPageHeader: typeof import('./src/@core/components/MVPageHeader.vue')['default']
    MvThumnail: typeof import('./src/@core/components/MvThumnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
